--- 
- 
  become: true
  become_user: root
  gather_facts: true
  hosts: localhost
  name: "install apache & php & mysql"
  tasks:
- 
  name: "Install apache2"
  package: "name=apache2 state=present"
- 
  name: "Install apache2-php5"
  package: "name=libapache2-mod-php state=present"
- 
  name: "Install php-cli"
  package: "name=php-cli state=present"
- 
  name: "Install php-mcrypt"
  package: "name=php-mcrypt state=present"
- 
  name: "Install phd-gd"
  package: "name=php-gd state=present"
- 
  name: "Install php-mysql"
  package: "name=php-mysql state=present"
- 
  name: "Install mysqlserver"
  package: "name=mysql-server state=present"
