---

- name: Install MySQL
  apt: name={{item}} state=present
  with_items:
  - python-mysqldb
  - mysql-server

- name: Start MySQL Service
  service: name=mysql state=started enabled=yes

- name: Create a New Database
  mysql_db: name=parco state=present collation=utf8_general_ci

- name: Update MySQL Password
  mysql_user: 
    name: testdb
    host: "{{item}}"
    password: "{{mysql_root_password}}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
  - web01
  - 127.0.0.1
  - ::1
  - localhost