---

- name:  Start Apache2
  service: name=apache2 state=started enabled=yes
 
- name: copy file
  copy: "src=files/info.php dest=/var/www/html/info.php mode=755"

- name: Restart Apache2 Server
  service: name=apache2 state=restarted
