- name: Install MYSQL Python Module
  apt: name=python-mysqldb state=present update_cache=yes

- name: create db user with all permissions 
  mysql_user:
    name: testdb
    password: testdb
    priv: '*.*:ALL'
    state: present

- name: Create database mytestdb
  mysql_db: db=mytestdb state=present

- name: Create a database Table
  command: mysql -u testdb -p testdb -e 'CREATE TABLE req (FirstName varchar(30), LastName varchar(30), Age int(10), CreatedAtTimestamp timestamp );' 


