---

- name: Install PHP Dependencies
  apt: name={{item}} state=present
  with_items:
  - python-software-properties
  - software-properties-common

- name: Add OndreJ PHP Repo
  raw: LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php -y

- name: Update Apt Cache
  apt: update_cache=yes

- name: Install PHP 7.2
  apt: name={{item}} state=present
  with_items:
  - php7.2
  - libapache2-mod-php7.2
  - php7.2-mysql
  - php7.2-curl
  - php7.2-json

- name: Restart Apache2
  service: name=apache2 state=restarted

- name: Create PHP Info File
  copy: src=phpinfo.php dest=/var/www/html/phpinfo.php

- name: Upload index.php File to the remote web directory
  copy: src=index.php dest=/var/www/html/

- name: Remove Default Apache page 
  file:
    path: /var/www/html/index.html
    state: absent